############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 3


[[main]]
name = "Services"
url = "/services"
weight = 2



# footer menu


[[footer]]
name = "Terms and Conditions"
url = "/terms-and-conditions"
weight = 5

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
